- app/src/main/res/layout/signing_activity.xml
- app/src/main/res/layout/verification_activity.xml
* Use Number input type to match requirements.
> Modify InputType in layout

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/minim/messenger/MainActivity.kt
- app/src/main/java/com/minim/messenger/SigningActivity.kt
- app/src/main/java/com/minim/messenger/VerificationActivity.kt
- app/src/main/res/layout/main_activity.xml
Co-authored-by: Micheline Medhat <MichelineMedhat@gmail.com>
> Add Phone Number Authentication

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/minim/messenger/SettingsActivity.kt
- app/src/main/java/com/minim/messenger/SigningActivity.kt
- app/src/main/java/com/minim/messenger/VerificationActivity.kt
- app/src/main/res/layout/settings_activity.xml
- app/src/main/res/layout/signing_activity.xml
Co-authored-by: Micheline Medhat <MichelineMedhat@gmail.com>
> Add Settings Activity

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/com/minim/messenger/ContactsAdaptor.kt
- app/src/main/java/com/minim/messenger/MainActivity.kt
- app/src/main/java/com/minim/messenger/Message.kt
- app/src/main/java/com/minim/messenger/SettingsActivity.kt
- app/src/main/java/com/minim/messenger/User.kt
- app/src/main/res/layout/contact_item.xml
- app/src/main/res/layout/main_activity.xml
Co-authored-by: Micheline Medhat <MichelineMedhat@gmail.com>
> Add Contacts RecyclerView

- app/src/main/java/com/minim/messenger/activities/MainActivity.kt
- app/src/main/java/com/minim/messenger/activities/SettingsActivity.kt
- app/src/main/java/com/minim/messenger/adaptors/ContactsAdaptor.kt
- app/src/main/java/com/minim/messenger/models/User.kt
- app/src/main/res/layout/contact_item.xml
- app/src/main/res/layout/main_activity.xml
- app/src/main/res/values/strings.xml
- Add Username Validation Rules.
- Improve MainActivity Layout.
- Add MainActivity backend.
> Populate Main activity

- app/src/main/java/com/minim/messenger/activities/ConversationActivity.kt
- app/src/main/java/com/minim/messenger/adaptors/ConversationAdaptor.kt
- app/src/main/java/com/minim/messenger/models/Message.kt
- app/src/main/java/com/minim/messenger/models/User.kt
* Make User Model parcelable.
* Create an empty constructor for the Message Model.
* Move MessageType enum into the Message Model.
* Rename MessageType to Type.
> Improve Models

- app/src/main/java/com/minim/messenger/activities/ContactsActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationActivity.kt
- app/src/main/java/com/minim/messenger/activities/SettingsActivity.kt
- app/src/main/java/com/minim/messenger/activities/SigningActivity.kt
- app/src/main/java/com/minim/messenger/activities/VerificationActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ContactsAdapter.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationAdapter.kt
- app/src/main/res/drawable/rounded_container.xml
- app/src/main/res/layout/activity_contacts.xml
- app/src/main/res/layout/activity_conversation.xml
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/layout/activity_signing.xml
- app/src/main/res/layout/activity_verification.xml
- app/src/main/res/layout/item_contact.xml
- app/src/main/res/layout/item_message_from.xml
- app/src/main/res/layout/item_message_to.xml
- app/src/main/res/values/integers.xml
- app/src/main/res/values/strings.xml
* Fix typo in "adaptors" package and classes; renamed to "adapters".
* Use underscores for naming IDs of views.
* Remove redundant attributes.
* Remove hardcoded username and pass contact username instead.
* Extract integer values.
* Fix warnings.
* Add padding to rounded_container itself instead of adding the same values to all EditTexts and Buttons.
> Refactor Code

- app/src/main/java/com/minim/messenger/activities/ContactsActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationActivity.kt
Co-authored-by: Micheline Medhat <MichelineMedhat@gmail.com>
> Add Real Time Listeners

- app/src/main/java/com/minim/messenger/activities/ConversationActivity.kt
* Add auto scrolling down in ConversationActivity.
* Stack messages from the bottom of the RecyclerView.
> Improve Conversation's RecyclerView

- app/src/main/java/com/minim/messenger/activities/ConversationActivity.kt
- app/src/main/java/com/minim/messenger/models/Conversation.kt
* Listen to modifications of the conversation opened and update UI.
* Detach Listener on going back.
* Validate message content to not be empty.
> Activate Conversation Real-Time Sync

- app/src/main/java/com/minim/messenger/activities/ContactsActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ContactsAdapter.kt
- app/src/main/java/com/minim/messenger/models/User.kt
- app/src/main/res/drawable/notification_blink.xml
- app/src/main/res/layout/activity_contacts.xml
- app/src/main/res/layout/item_contact.xml
* Populate contacts RecyclerView the first time using SnapshotListener.
* Listen to modifications of the conversations shared and update UI.
* Listen to new contacts and add them to the contacts RecyclerView.
* Update contact item layout to include a notification flag.
> Activate Contacts' Real-Time Sync

- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationsActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationsAdapter.kt
- app/src/main/java/com/minim/messenger/models/Conversation.kt
- app/src/main/java/com/minim/messenger/models/Message.kt
* Create messages Firestore Collection.
> Add Seen Strategy

- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationsAdapter.kt
- app/src/main/java/com/minim/messenger/models/Conversation.kt
- app/src/main/java/com/minim/messenger/models/Message.kt
Co-authored-by: Michael Safwat <michaelsafwat.hanna@gmail.com>
> Improve Fetching Messages Flow

- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationsActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationsAdapter.kt
- app/src/main/java/com/minim/messenger/models/Conversation.kt
- app/src/main/java/com/minim/messenger/models/Message.kt
* Listen to Messages documents instead of conversations documents.
* Delete overdue messages on conversation click.
* Fix notification bug.
> Delete Overdue Messages

- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationsActivity.kt
- app/src/main/java/com/minim/messenger/activities/SettingsActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationsAdapter.kt
- app/src/main/java/com/minim/messenger/models/Conversation.kt
> Use User UID and Conversation ID

- app/src/main/java/com/minim/messenger/activities/ConversationsActivity.kt
> Fix Push Notification Bug

- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationsActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationsAdapter.kt
- app/src/main/java/com/minim/messenger/adapters/MessagesAdapter.kt
- app/src/main/java/com/minim/messenger/models/Message.kt
* Add default values for type, seen and sentOn properties.
* Exclude the type property from Firestore.
* Add encrypt and decrypt methods.
> Improve Message Model

- app/build.gradle
- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/models/Message.kt
- app/src/main/res/layout/activity_conversation_log.xml
- app/src/main/res/values/integers.xml
- app/src/main/res/values/styles.xml
* Add Picker UI Controls.
* Make 24 Hours default and maximum customizable duration's value from
duration settings instead of Message model.
* Modify Message edit text input type to capitalize sentences.
> Add Customized Message Duration Settings

- app/src/main/java/com/minim/messenger/activities/ConversationLogActivity.kt
- app/src/main/java/com/minim/messenger/activities/ConversationsActivity.kt
- app/src/main/java/com/minim/messenger/adapters/ConversationsAdapter.kt
> Fix Notification bug

- app/src/main/java/com/minim/messenger/activities/SettingsActivity.kt
> Add Delete/Sign-out Backend
